name: Lint Shell Scripts

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
    
    - name: Run ShellCheck
      run: |
        find . -name "*.sh" -type f -exec shellcheck {} +
    
    - name: Run custom lint script
      run: |
        chmod +x scripts/lint.sh
        ./scripts/lint.sh
